name: Push image to Dockerhub and deploy on Elastic Beanstalk

on:
  push:
    branches:
    - main

jobs:
  build_docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
        logout: true
#
    - name: Build Server image
      run: docker build -t francislemay/hello-express -f ./Dockerfile .

    - name: Tag Server Image
      run: docker tag francislemay/hello-express francislemay/hello-express:latest

    - name: Push to Dockerhub
      run: docker push francislemay/hello-express

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
        aws_secret_key: ${{secrets.AWS_ACCESS_SECRET_KEY}}
        application_name: hello
        environment_name: Hello-env
        version_label: "hello-latest"
        region: us-east-1
     